# Generated by Django 4.2.9 on 2024-02-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_brand_product_star_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='star',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
