# Generated by Django 4.2.9 on 2024-02-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
