# Generated by Django 4.2.9 on 2024-02-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_brand_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
