# Generated by Django 4.2.9 on 2024-02-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_brand_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.DeleteModel(
            name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
