# Generated by Django 4.2.9 on 2024-02-10 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_product_image4_remove_product_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
