# Generated by Django 4.2.9 on 2024-02-10 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_product_color_remove_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='color2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color2', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='color3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color3', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='size2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size2', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='size3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size3', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='color2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.color2'),
        ),
        migrations.AddField(
            model_name='product',
            name='color3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.color3'),
        ),
        migrations.AddField(
            model_name='product',
            name='size2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.size2'),
        ),
        migrations.AddField(
            model_name='product',
            name='size3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.size3'),
        ),
    ]
