# Generated by Django 4.2.9 on 2024-02-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_product_color2_remove_product_color3_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='color2',
        ),
        migrations.DeleteModel(
            name='color3',
        ),
        migrations.DeleteModel(
            name='size2',
        ),
        migrations.DeleteModel(
            name='size3',
        ),
        migrations.AddField(
            model_name='product',
            name='price_off',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
