# Generated by Django 4.2.9 on 2024-02-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_delete_color2_delete_color3_delete_size2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_Detail2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=255)),
                ('address1', models.TextField()),
                ('address2', models.TextField(blank=True, null=True)),
                ('code_posti', models.IntegerField()),
            ],
        ),
    ]
