# Generated by Django 4.2.9 on 2024-02-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_cart_detail2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
