# Generated by Django 4.2.9 on 2024-03-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_product_star_c_alter_product_star_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='star_c',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='star_t',
            field=models.IntegerField(default=0),
        ),
    ]
