# Generated by Django 4.2.9 on 2024-01-26 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='content',
            new_name='Newsletters',
        ),
    ]
