# Generated by Django 4.2.9 on 2024-01-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_contactform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='contactform',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactform',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
