# Generated by Django 4.2.9 on 2024-01-27 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_contactform_options_contactform_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='updated_date',
        ),
    ]
