# Generated by Django 4.2.9 on 2024-02-01 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_newsletters_options_newsletters_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletters',
        ),
    ]
