# Generated by Django 4.2.9 on 2024-02-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_newsletters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletters',
            options={},
        ),
        migrations.RemoveField(
            model_name='newsletters',
            name='date',
        ),
    ]
