# Generated by Django 4.2.9 on 2024-02-18 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0020_delete_color2_delete_color3_delete_size2_and_more"),
        ("accounts", "0004_remove_cart_is_paid_remove_cart_products_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.product"
            ),
        ),
    ]
