# Generated by Django 4.2.9 on 2024-02-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0020_delete_color2_delete_color3_delete_size2_and_more"),
        ("accounts", "0006_cart_is_paid_cart_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="product",
        ),
        migrations.AddField(
            model_name="cart",
            name="product",
            field=models.ManyToManyField(to="store.product"),
        ),
    ]
