# Generated by Django 4.2.9 on 2024-03-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price_off',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
