# Generated by Django 4.2.9 on 2024-03-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_cart_price_off'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price_off',
        ),
    ]
