# Generated by Django 4.2.9 on 2024-02-29 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zarinpal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='total_price',
            new_name='TotalPrice',
        ),
        migrations.RenameField(
            model_name='totalprice',
            old_name='total_price',
            new_name='total',
        ),
    ]
