# Generated by Django 4.2.9 on 2024-03-01 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zarinpal', '0003_totalprice_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalprice',
            name='user',
        ),
    ]
